from PIL import Image, ImageDraw, ImageFont
import os
from pathlib import Path

def create_mock_image(filename, text, size=(1200, 675), bg_color=(235, 235, 240)):
    img = Image.new('RGB', size, color=bg_color)
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("DejavuSans-Bold.ttf", 36)
    except:
        font = ImageFont.load_default()
        
    d.text((50, size[1]//2 - 50), text, fill=(40, 40, 70))
    d.text((50, size[1]//2 + 50), "Generated by Gemini Banana Pro", fill=(80, 80, 120))
    d.text((50, size[1]//2 + 100), "Style: Sketch / blueprint", fill=(80, 80, 120))
    
    img.save(filename, format='JPEG', quality=85)
    print(f"Created {filename} - {os.path.getsize(filename)/1024:.1f} KB")

out_dir = Path('/home/ubuntu/banunu-blog/content/posts/dau-tu-ha-tang-ai-nang-luong-hat-nhan-2026')

# 1. Hero image (16:9 -> 1200x675)
create_mock_image(out_dir / 'hero.jpg', "Hero Image: Blueprint of mega data center + nuclear reactor")

# 2. In-body image (16:9 -> 1200x675)
create_mock_image(out_dir / 'section-1.jpg', "In-body: Power grid flowchart connecting nuclear to servers")

# 3. OG image (1200x630, <600KB)
create_mock_image(out_dir / 'og-image.jpg', "OG Image: Blueprint of data center + nuclear (1200x630)", size=(1200, 630))

