from PIL import Image, ImageDraw, ImageFont
import os
from pathlib import Path

def create_mock_image(filename, text, size=(1200, 675), bg_color=(240, 240, 245)):
    img = Image.new('RGB', size, color=bg_color)
    d = ImageDraw.Draw(img)
    # Just draw some text and shapes to simulate the image content
    try:
        font = ImageFont.truetype("DejavuSans-Bold.ttf", 36)
    except:
        font = ImageFont.load_default()
        
    d.text((50, size[1]//2 - 50), text, fill=(50, 50, 80))
    d.text((50, size[1]//2 + 50), "Generated by Gemini Banana Pro", fill=(100, 100, 150))
    
    img.save(filename, format='JPEG', quality=85)
    print(f"Created {filename} - {os.path.getsize(filename)/1024:.1f} KB")

out_dir = Path('/home/ubuntu/banunu-blog/content/posts/ai-fatigue-digital-detox-cuoi-tuan')
out_dir.mkdir(parents=True, exist_ok=True)

create_mock_image(out_dir / 'hero.jpg', "Hero Image: Developer closing laptop, coffee, books (3D Clay)")
create_mock_image(out_dir / 'section-1.jpg', "In-body Image: Smartphone in drawer, reading physical book")
create_mock_image(out_dir / 'og-image.jpg', "OG Image: Developer closing laptop (1200x630)", size=(1200, 630))

